### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by hawkeyebs420** [avytrv/cmoa_downloader_userscript#1]
Hi, I was wondering how this downloader works and if it still works? I'd like to download some ebooks for personal use only from the site.

**Comment by avytrv** [comment]
Hi, thanks for checking out the downloader.

This is a user script that can be used by downloading a browser extension such as Tampermonkey. More information on how to do that [here](https://greasyfork.org/). You can then install the script [here](https://greasyfork.org/en/scripts/438701-cmoa-jp-downloader). The script will show up as an orange tab in cmoa.jp's comic reader. 

Right now, it doesn't support downloading light novels, only comics, and sometimes hangs while downloading. If it hangs, you can try refreshing the page or trying again at a later time. I never expected that anyone would want to use my script, but if there are any problems or features you'd be interested in, let me know and I'll see what I can do.

**Comment by hawkeyebs420** [comment]
Thank you very much for the help. Initially tried on incognito mode, but it didn't work. Worked fine once I exited it. Is there a way to improve resolution or is it already downloading the images at their max resolution?

**Comment by avytrv** [comment]
Glad to be of help. 😄 If you'd like to download in incognito mode, you may have to enable the user script extension in incognito mode, since browsers will often disable all extensions by default. As for the resolution, unfortunately it is already downloading at the max available from cmoa.

**Comment by hawkeyebs420** [comment]
Understood. I was wondering if this code could be rewritten for a site like Bookwalker? I'm not sure if they use the same speedreader, but was wondering if you had thought about other sites?

**Comment by avytrv** [comment]
After poking around a bit, it looks like Bookwalker uses a different and more complicated reader than cmoa. Right now, I'm not sure that I'd be able to write an extension for it.
