### ISSUE TITLE
hope to make one for dmm

### ISSUE THREAD

**Issue by pumpkissster** [avytrv/cmoa_downloader_userscript#2]
Thank you very much for making this software！It's very useful！
I wonder if you can make one for dmm，I will be very grateful！Thank you so much！

**Comment by avytrv** [comment]
Thank you for the kind words! Unfortunately, my skill level is not good enough to make one for DMM. Due to personal reasons, I will be deleting this repository soon, but the script will still be available here: https://greasyfork.org/en/scripts/445038-cmoa-jp-downloader
